# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealUsers', '0004_auto_20170422_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='home, Street, City, District, Country', max_length=1024),
        ),
    ]
